zmisc/test1/tal1/core/urls.py
from django.urls import path
from core import api, views

app_name = 'core'
urlpatterns = [
    path('', views.home, name="home"),
    path('998421.txt/', views.response_200, name="res_enamad"),
    path('exams/', views.exams, name="exams"),
    path('rules/', views.rules, name="rules"),
    path('about_us/', views.about_us, name="about_us"),
    path('pcm/', views.pcm, name="pcm"),
    path('evaluation/', views.evaluation, name="evaluation"),
    # APIs
    path('api/file-upload', api.FileUpload.as_view(), name="file_upload"),
    path('api/location/', api.Location.as_view(), name="location"),
    path('api/config/', api.Config.as_view(), name="config"),
    path('api/home_job/', api.Home_job.as_view(), name="home_job"),
    path('api/urls/', api.Urls.as_view(), name="panel_urls"),
    path('api/user-info/', api.UserInfo.as_view(), name="user_info"),
]

zmisc/test1/tal1/log/urls.py
from django.urls import path, include


app_name = 'log'
urlpatterns = [
    path('api/', include('log.api.urls', namespace='api')),
    ]

zmisc/test1/tal1/core/models.py
from django.db import models

# Create your models here.
class Location(models.Model):
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)

zmisc/test1/tal1/core/views.py
from django.template import loader
from django.views import View
from django.http import HttpResponse
from common.common import ConfigMethods
from job.models import Job


def home(request):
    return StandardRender.render(request, 'home.html', context={
        'jobs_count': Job.objects.filter(status="active").count(),
    })


def response_200(request):
    return HttpResponse('')


class StandardRender():
    @classmethod
    def get_footer_data(self):
        data = {'footer': {
            'copyright_name': ConfigMethods.get_config('contact', 'copy_right'),
            'copyright_url': ConfigMethods.get_config('url', 'copy_right'),
            'address': ConfigMethods.get_config('contact', 'address'),
            'phone': ConfigMethods.get_config('contact', 'phone'),
            'email': ConfigMethods.get_config('contact', 'email'),
            'abour_url': ConfigMethods.get_config('url', 'about'),
            'contact_url': ConfigMethods.get_config('url', 'contact'),
            'about_us': ConfigMethods.get_config('contact', 'about_us'), 
        }}
        useful_links_list = ConfigMethods.get_configs_list(['useful_links'])
        social_media_list = ConfigMethods.get_configs_list(['social_media'])
        useful_links = {}
        for link in useful_links_list:
            useful_links.update({link.get('key', ''): link.get('value', '')})

        social_media = {}
        for s in social_media_list:
            social_media.update({s.get('key', ''): s.get('value', '')})

        data['footer'].update({'useful_links': useful_links})
        data['footer'].update({'social_media': social_media})
        return data

    @staticmethod
    def render(request, template_name, context=None, content_type=None, status=None, using=None):
        """
        Return a HttpResponse whose content is filled with the result of calling
        django.template.loader.render_to_string() with the passed arguments.

        And Add footer data to content.
        """
        if context is None:
            context = {}
        context.update(StandardRender.get_footer_data())
        content = loader.render_to_string(
            template_name, context, request, using=using)
        return HttpResponse(content, content_type, status)


def exams(request):
    render = StandardRender.render
    return render(request, 'exams.html')

def rules(request):
    render = StandardRender.render
    return render(request, 'rules.html')

def about_us(request):
    render = StandardRender.render
    return render(request, 'about_us.html')

def pcm(request):
    render = StandardRender.render
    return render(request, 'pcm.html')
def evaluation(request):
    return StandardRender.render(request, 'evaluation_and_development.html', context={})

zmisc/test1/tal1/core/templates/about_us.html
{% extends 'panel.html' %}
{% load static %}

{% block home_style %}
   <link rel="stylesheet" type="text/css" href="{% static  'pages/about_us/about_us.min.css' %}">
   
{% endblock %}

{% block home_content %}
   <div id="element___about_us_page">
      <about_us :context="variablesData"></about_us>
   </div>
{% endblock %}

{% block home_js %}
   
   <script src="{% static 'pages/about_us/about_us.min.js' %}"></script>
   <script>
         var context = {
    image: "{% static '/base/img/aboutus.jpg' %}",
}  
         </script>
   <script>
      let vue___about_us_page = new Vue({
         el: '#element___about_us_page',
         data: {
            variablesData: context,
         },
         created() {
            document.title = 'درباره بورس';
         },
         components: {
            "about_us": about_us,
         }
      });
   </script>
{% endblock %}
   

zmisc/test1/tal1/core/templates/base_error.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ERROR {% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'core/css/error.css' %} ">
{% endblock %}

{% block content %}
    <div class="error-main">
        <!-- div photo -->
        <div>
            {% block error_img %}
            {% endblock %}
        </div>
        <!-- div text -->
        <div class="error-text">
            {% block error_msg %}
            {% endblock %}
        </div>
        <!-- div button -->
        <div class="button-error">
            <button class="ui grey basic button button-error" onclick="window.location ='{% url 'core:home' %}' ">
                <i class="material-icons">home</i>
                خانه
            </button>
            <!-- <button class="ui grey basic button button-error" {% if request.user.role == 'applicant' %} onclick = "window.location.href ='{% url 'resume:resume' %}';" {%else%} onclick="window.location.href = '{%url 'company:jobs'%}';" {%endif%}>
                <i class="material-icons">person</i>
                پروفایل شما
            </button> -->
        </div>
    </div>
{% endblock %}
{% block home_js %}

{% endblock %}

zmisc/test1/tal1/core/templates/evaluation_and_development.html
{% extends 'panel.html' %}
{% load static %}

{% block home_style %}
   <link rel="stylesheet" type="text/css" href="{% static  'pages/evaluation_and_development/evaluation_and_development.min.css' %}">
   
{% endblock %}

{% block home_content %}
   <div id="element___evaluation_and_development_page">
      <evaluation_and_development :context="variablesData"></evaluation_and_development>
   </div>
{% endblock %}

{% block home_js %}
   
   <script src="{% static 'pages/evaluation_and_development/evaluation_and_development.min.js' %}"></script>
   <script>
         var context = {
    image:"{%static '/base/img/evalution.png'%}"
}  
         </script>
   <script>
      let vue___evaluation_and_development_page = new Vue({
         el: '#element___evaluation_and_development_page',
         data: {
            variablesData: context,
         },
         created() {
            document.title = 'کانون ارزیابی و توسعه';
         },
         components: {
            "evaluation_and_development": evaluation_and_development,
         }
      });
   </script>
{% endblock %}
   

zmisc/test1/tal1/core/templates/exams.html
{% extends 'panel.html' %}
{% load static %}

{% block home_style %}
   <link rel="stylesheet" type="text/css" href="{% static  'pages/exams/exams.min.css' %}">
   
{% endblock %}

{% block home_content %}
   <div id="element___exams_page">
      <exams :context="variablesData"></exams>
   </div>
{% endblock %}

{% block home_js %}
   
   <script src="{% static 'pages/exams/exams.min.js' %}"></script>
   <script>
         var context = {
    exam: "{% static '/base/img/exam4.png' %}",
}  
         </script>
   <script>
      let vue___exams_page = new Vue({
         el: '#element___exams_page',
         data: {
            variablesData: context,
         },
         created() {
            document.title = 'آزمون ها';
         },
         components: {
            "exams": exams,
         }
      });
   </script>
{% endblock %}
   

zmisc/test1/tal1/core/templates/home.html
{% extends 'panel.html' %}
{% load static %}

{% block home_style %}
   <link rel="stylesheet" type="text/css" href="{% static  'pages/home/home.min.css' %}">
   
{% endblock %}

{% block home_content %}
   <div id="element___home_page">
      <home :context="variablesData"></home>
   </div>
{% endblock %}

{% block home_js %}
   
   <script src="{% static 'pages/home/home.min.js' %}"></script>
   <script>
         var context = {
    // img_home: "{% static '/base/img/bg-home.png' %}",
    img_one: "{% static '/base/img/one.webp' %}",
    img_two: "{% static '/base/img/two.webp' %}",
    img_three: "{% static '/base/img/three.webp' %}",
    img_ifc: "{% static '/base/img/aboutus.webp' %}",
    logo_one: "{% static '/base/img/otherslogo1.webp' %}",
    logo_two: "{% static '/base/img/otherslogo2.webp' %}", 
    logo_three: "{% static '/base/img/otherslogo3.webp' %}", 
    logo_four: "{% static '/base/img/otherslogo4.webp' %}",
    logo_five:"{% static '/base/img/otherslogo5.webp' %}",
    job_page_url: "{% url 'job:job_detail' 0 %}",
    jobs_list_api: "{% url 'job:api:search' %}",
    jobs_count: Number("{{jobs_count}}"),
    jobs_list_url: "{% url 'job:jobs_list' %}",
    jobs_starred_api: "{% url 'job:api:starred_job' %}",
    special_jobs_api: "{% url 'job:api:home_suggest_job' %}",
    company_list_api: "{% url 'company:api:company_list' %}",
    job_home:"{% static '/base/img/job-home.webp' %}",
    exam_home:"{% static '/base/img/exam-home.webp' %}",
    cv_home:"{% static '/base/img/cv-home.webp' %}",
    company_home:"{% static '/base/img/company-home2.webp' %}",
    advertising_home:"{% static '/base/img/advertising-home.webp' %}",
    job_list:"{%url 'job:jobs_list' %}",
    job_info:"{%url 'job:job_info' %}",
    company_list:"{%url 'company:company_list'%}",
    resume_maker:"{%url 'resume:landing'%}",
    exam:"{%url 'core:exams' %}",
    ifc_site:"https://domain.local/",
    cons_request_api:"{%url 'ticket:api:consultation_request' %}",
}
         </script>
   <script>
      let vue___home_page = new Vue({
         el: '#element___home_page',
         data: {
            variablesData: context,
         },
         created() {
            document.title = 'بورس';
         },
         components: {
            "home": home,
         }
      });
   </script>
{% endblock %}
   

zmisc/test1/tal1/core/templates/pcm.html
{% extends 'panel.html' %}
{% load static %}

{% block home_style %}
   <link rel="stylesheet" type="text/css" href="{% static  'pages/pcm/pcm.min.css' %}">
   
{% endblock %}

{% block home_content %}
   <div id="element___pcm_page">
      <pcm :context="variablesData"></pcm>
   </div>
{% endblock %}

{% block home_js %}
   
   <script src="{% static 'pages/pcm/pcm.min.js' %}"></script>
   <script>
         var context = {
    title: 'سلام به دنیا'
}  
         </script>
   <script>
      let vue___pcm_page = new Vue({
         el: '#element___pcm_page',
         data: {
            variablesData: context,
         },
         created() {
            document.title = 'ارکان بازار سرمایه';
         },
         components: {
            "pcm": pcm,
         }
      });
   </script>
{% endblock %}
   

zmisc/test1/tal1/core/templates/rules.html
{% extends 'panel.html' %}
{% load static %}

{% block home_style %}
   <link rel="stylesheet" type="text/css" href="{% static  'pages/rules/rules.min.css' %}">
   
{% endblock %}

{% block home_content %}
   <div id="element___rules_page">
      <rules :context="variablesData"></rules>
   </div>
{% endblock %}

{% block home_js %}
   
   <script src="{% static 'pages/rules/rules.min.js' %}"></script>
   <script>
         var context = {
    title: 'سلام به دنیا'
}  
         </script>
   <script>
      let vue___rules_page = new Vue({
         el: '#element___rules_page',
         data: {
            variablesData: context,
         },
         created() {
            document.title = 'قوانین و مقررات';
         },
         components: {
            "rules": rules,
         }
      });
   </script>
{% endblock %}
   