zmisc/test1/tal1/log/urls.py
from django.urls import path, include


app_name = 'log'
urlpatterns = [
    path('api/', include('log.api.urls', namespace='api')),
    ]

zmisc/test1/tal1/notification/urls.py
from django.urls import path, include
from notification import views
from . import api
app_name = 'notification'
urlpatterns = [
    path('', views.notification, name="notification"),
    path('notification_details/<int:pk>/', views.notification_details, name="notification_details"),
    path('api/notification/', api.ChangeNotification.as_view(), name="notification_api"),
    path('api/show_notification/', api.ShowNotifications.as_view(), name="show_notification_api"),
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

zmisc/test1/tal1/notification/models.py
from django.db import models
from accounts.models import User
from company.models import Company
from persiantools.jdatetime import JalaliDate
from persiantools import characters, digits
from django.utils import timezone


class Notification(models.Model):
    notification_type = models.CharField(max_length=50, default='resume')
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="notification_reciever")
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="notification_sender", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(Company, on_delete=models.PROTECT, related_name="related_company", null=True,
                                blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    unread = models.BooleanField(default=True)
    settings = models.JSONField(null=True, blank=True)

    def get_persian_created_at(self):
        date = JalaliDate(self.created_at)
        return digits.en_to_fa(str(date.year) + "/" + str(date.month) + "/" + str(date.day))

    @property
    def time_from_creat(self):
        date = timezone.now().replace(tzinfo=None) - self.created_at.replace(tzinfo=None)
        if date.days > 0:
            return " %s روز قبل" % (str(date.days))
        elif date.seconds >= 3600:
            return " %s ساعت قبل" % (str(int(date.seconds / 3600)))
        else:
            return " %s دقیقه قبل" % (str(int(date.seconds / 60)))

zmisc/test1/tal1/notification/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Notification
from common.common import CoreFunctions
from core.views import  StandardRender
render = StandardRender.render


@login_required()
def notification(request):
    queryset = Notification.objects.filter(user=request.user).order_by('-created_at')
    page_obj = CoreFunctions.pagination(request, queryset)
    return render(request, 'notification.html', {'notifications': page_obj})


@login_required()
def notification_details(request, pk):
    queryset = get_object_or_404(Notification, pk=pk, user=request.user)
    queryset.unread = False
    queryset.save()
    return render(request, 'notification_details.html', {'notification': queryset})

zmisc/test1/tal1/notification/templates/email.html
{% load static %}
<style>
    .up-head {
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        align-content: center;
        align-items: center;
        justify-content: space-between;
        padding: 0 20px;
    }

    .logo-header {
        display: flex;
        flex-direction: row;
        align-content: center;
        align-items: center;
        cursor: pointer;
    }

    .logo-header img {
        width: 140px;
        margin-top: 4px;
    }

    .menu-header {
        background-color: #eaf3ff;
        box-shadow: 0px 16px 25px 4px rgba(0, 0, 0, 2%);
        transition: all 1s;
    }

    .main-div {
        width: 100%;
    }

    .text_box{
        margin: 5%;
        box-shadow: 0 5px 25px 4px rgb(0 0 0 / 6%);
        width: 80%;
        border-radius: 12px;
        padding: 4%;
        margin-bottom: 25px;
    }
</style>

<body dir="rtl">
    <header class="menu-header">
        <div class="up-head">
            <div class="logo-header" @click="redirectToHomePage()">
                <img src="{% static '/base/img/logocompany.png' %} ">
            </div>
            <div>
                <p>مرکز</p>
            </div>
        </div>
    </header>
    <div class="main-div">
        <div class="text_box">
            <p>سلام {{ user.get_full_name }} عزیز</p>
            <h2>{{ title }}</h2>
            <p>{{ description }}</p>
        </div>
        <p>ورود به بورس {{ domain }}</p>
    </div>
</body>

zmisc/test1/tal1/notification/templates/notification.html
{% extends 'panel.html' %}
{% load static %}
{% block title %} اعلان ها {% endblock %}
{% block employee_style %}
    <link rel="stylesheet" href="{% static '/notification/css/notifs.css' %} ">
{% endblock %}
{% block header %}
{% endblock %}
{% block main %}
    <div>
        <div class="notifMain">
            <div class="notifContent">
                <div class="ui breadcrumb notif_title">
                    <h1 class="section">اعلان ها</h1>
                </div>
                <div class="ui pointing secondary menu notifMenu">
                    <!-- <a class="item active-title item1" data-tab="first">همه</a>
                    <a class="item item1" data-tab="second"></a> -->
                    <div class="filter-div">
                        <!-- <a class="item item1" data-tab="third"></a> -->
                        <div id="checked-checkbox" class="tooltip">
                            <i class="material-icons notification-icons delete" data-tooltip="حذف پیام" onclick="call_api('delete')">delete</i>
                        </div>
                        <div id="text" class="tooltip">
                            <i class="material-icons notification-icons mark-as-read" data-tooltip="علامت به عنوان خوانده شده " onclick="call_api('unread')">mark_as_unread</i>
                        </div>
                        <!-- <a class="item item2 disabled" data-tab="third">
                            <i class="material-icons">filter_alt</i>فیلتر ها
                        </a> -->
                    </div>
                </div>
                {% if notifications %}
                <div class="list-notif">
                        <table class="ui celled unstackable table table_items">
                            <thead>
                            <tr>
                                <th></th>
                                <!-- <th>شناسه پیام</th> -->
                                <th>عنوان</th>
                                <th>پیش نمایش</th>
                                <th>زمان</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in notifications %}
                                <tr class="{% if item.unread %} cells {% else %} unread-cells {% endif %}"
                                    onclick="ridirect({{ item.pk }})">
                                    <td class="general-cells">
                                        <input class="Checkbox" type="checkbox" id="checkbox{{ item.pk }}"
                                               value="{{ item.pk }}"
                                               onclick="event.stopPropagation(); myFunction({{ item.pk }},'{{ item.unread }}')"
                                        >
                                    <!-- <td>{{ item.pk }}</td> -->
                                    <td>{{ item.title }}</td>
                                    <td id="show-more{{ item.description }}">
                                        {{ item.description|truncatechars_html:30 }}
                                    </td>
                                    <td>{{ item.get_persian_created_at }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        {% include 'inc/not_found.html' %}
                    {% endif %}
                </div>
                {% if notifications %}
                    {% with pagination=notifications %}
                        {% include 'inc/pagination.html'%}
                    {% endwith %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block employee_js %}
    <script>
        var delete_count = 0;
        var mark_as_read_count = 0;

        function myFunction(pk, unread) {
            var checkBox = document.getElementById("checkbox" + pk);
            var delet = document.getElementById("checked-checkbox");
            var mark_as_read = document.getElementById("text");

            if (checkBox.checked == true) {
                if (unread == 'True') {
                    mark_as_read_count = mark_as_read_count + 1;
                }
                delete_count = delete_count + 1;
            }
            if (checkBox.checked == false) {
                if (unread == 'True') {
                    mark_as_read_count = mark_as_read_count - 1;
                }
                delete_count = delete_count - 1;
            }
            if (delete_count > 0) {
                delet.style.display = "block";
            }
            if (mark_as_read_count > 0) {
                mark_as_read.style.display = "block";
            }

            if (delete_count == 0) {
                delet.style.display = "none";
            }
            if (mark_as_read_count == 0) {
                mark_as_read.style.display = "none";
            }
        }

        function ridirect(pk) {
            var url = "{%url 'notification:notification_details' pk=0 %}".split('/');
            url.pop();
            url.pop();
            url.push(pk);
            goToPage(url.join('/'));
        }
    </script>

    <script>
        // call delete notification api
        function call_api(api_type) {
            if (api_type == 'delete') {
                var method = 'DELETE'
            } else if (api_type == 'unread') {
                var method = 'POST'
            }

            let pk = ($('.Checkbox:checked').map(function () {
                return this.value;
            }).get().join(','));
            console.log(pk)
            const csrftoken = getCookie('csrftoken');
            (async () => {
                var data = new FormData()
                data.append("pk", pk);
                const rawResponse = await fetch('{% url 'notification:notification_api' %}', {
                    method: method,
                    headers: {
                        'X-CSRFToken': csrftoken
                    },
                    body: data
                });
                const content = await rawResponse.status;
                if (content == 200) {
                    window.location.href = '{% url "notification:notification" %}'
                }else {
                    alert("مشکلی پیش آمده !!!")
                }
            })();
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }


    </script>
{% endblock %}

zmisc/test1/tal1/notification/templates/notification_details.html
{% extends 'panel.html' %}
{% load static %}
{% block title %} {% endblock %}
{% block employee_style %}
    <link rel="stylesheet" href="{% static 'notification/css/notif_detail.css' %} ">
{% endblock %}

{% block main %}
    <div>
        <div class="notifDetailContent">
            <div class="detailContents">
                <div class="title">
                    <div class="title-content">
                        <div class="ui breadcrumb">
                            <div class="section">اعلان ها</div>
                            <div class="divider"> / </div>
                            <div class="active section">{{ notification.title }}</div>
                        </div>
                    </div>
                </div>
                <div class="ui secondary segment details">
                    <p>{{ notification.description }}</p>
                </div>
            </div>
            <div class="buttons">
                <button class="ui basic grey button" onclick="got_to_previous_page();">بازگشت به صفحه قبل</button>
                {% if notification.company %}
                    <button class="ui basic grey button"
                            onclick="redirect('{%url 'company:company_detail' pk=0 %}','{{ notification.company.pk }}');">
                        صفحه {{ notification.company.title }}</button>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block employee_js %}
    <script>
        function got_to_previous_page() {
            goToPage(document.referrer);
        }
    </script>
{% endblock %}